import { useCallback, useEffect, useState } from 'react'
import { Plus, Search, ShieldPlus, Trash2, UserRound } from 'lucide-react'
import { authApi, citizenApi, documentApi } from '../api/client'
import { PageHeader } from '../components/AppShell'
import { Alert, Button, EmptyState, Field, Modal, Pagination, SkeletonRows, StatusBadge } from '../components/ui'
import { CITIZEN_STATUSES, pretty } from '../constants'

const emptyCitizen = { name: '', nic: '', email: '', mobile: '', address: '', status: 'ACTIVE' }

function CitizenForm({ initial = emptyCitizen, onClose, onSave }) {
  const [form, setForm] = useState({ ...emptyCitizen, ...initial }); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const update = (e) => setForm({ ...form, [e.target.name]: e.target.value })
  const submit = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { await onSave(form); onClose() } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <form className="form-grid" onSubmit={submit}>{error && <div className="span-2"><Alert>{error}</Alert></div>}<Field label="Full name"><input name="name" required maxLength="100" value={form.name} onChange={update} /></Field><Field label="National ID / NIC"><input name="nic" required maxLength="20" value={form.nic} onChange={update} /></Field><Field label="Email"><input name="email" type="email" required maxLength="100" value={form.email} onChange={update} /></Field><Field label="Mobile"><input name="mobile" type="tel" required maxLength="15" value={form.mobile} onChange={update} /></Field><Field label="Address"><textarea name="address" required maxLength="255" rows="3" value={form.address} onChange={update} /></Field><Field label="Account status"><select name="status" value={form.status} onChange={update}>{CITIZEN_STATUSES.map((s) => <option key={s} value={s}>{pretty(s)}</option>)}</select></Field><div className="form-actions span-2"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button loading={busy}>Save citizen</Button></div></form>
}

function AdminTools({ onClose }) {
  const [tab, setTab] = useState('user'); const [form, setForm] = useState({ username: '', email: '', password: '', role: 'SERVICE_AGENT', documentId: '' }); const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false)
  const submit = async (e) => { e.preventDefault(); setBusy(true); setNotice(null); try { if (tab === 'user') { await authApi.adminRegister({ username: form.username, email: form.email, password: form.password, roles: [form.role] }); setNotice({ type: 'success', text: `${pretty(form.role)} account created.` }) } else { await documentApi.remove(form.documentId); setNotice({ type: 'success', text: `Document #${form.documentId} deleted.` }) } } catch (err) { setNotice({ type: 'error', text: err.message }) } finally { setBusy(false) } }
  return <><div className="tabs"><button className={tab === 'user' ? 'active' : ''} onClick={() => setTab('user')}>Create staff user</button><button className={tab === 'document' ? 'active' : ''} onClick={() => setTab('document')}>Delete document</button></div>{notice && <Alert type={notice.type}>{notice.text}</Alert>}<form className="form-grid" onSubmit={submit}>{tab === 'user' ? <><Field label="Username"><input required minLength="3" maxLength="50" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} /></Field><Field label="Email"><input type="email" required maxLength="100" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></Field><Field label="Temporary password" hint="Communicate through an approved secure channel."><input type="password" required minLength="6" maxLength="100" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></Field><Field label="Role"><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="SERVICE_AGENT">Service Agent</option><option value="ADMIN">Administrator</option></select></Field></> : <Field label="Document ID" hint="The backend does not expose an admin document-list endpoint, so an exact ID is required."><input type="number" min="1" required value={form.documentId} onChange={(e) => setForm({ ...form, documentId: e.target.value })} /></Field>}<div className="form-actions span-2"><Button type="button" variant="secondary" onClick={onClose}>Close</Button><Button variant={tab === 'document' ? 'danger' : 'primary'} loading={busy}>{tab === 'document' ? 'Delete document' : 'Create user'}</Button></div></form></>
}

export function CitizensPage() {
  const [result, setResult] = useState({ content: [], number: 0, totalPages: 0, totalElements: 0 }); const [query, setQuery] = useState(''); const [page, setPage] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState(null); const [creating, setCreating] = useState(false); const [tools, setTools] = useState(false)
  const load = useCallback(() => { setLoading(true); citizenApi.list({ query, page, size: 10 }).then(setResult).catch((e) => setError(e.message)).finally(() => setLoading(false)) }, [query, page])
  useEffect(load, [load])
  const deactivate = async (citizen) => { if (!window.confirm(`Deactivate ${citizen.name}?`)) return; try { await citizenApi.deactivate(citizen.id); load() } catch (e) { setError(e.message) } }
  return <><PageHeader eyebrow="Administration" title="Citizen management" description="Create, search and maintain citizen profiles." action={<div className="header-actions"><Button variant="secondary" onClick={() => setTools(true)}><ShieldPlus size={18} />Admin tools</Button><Button onClick={() => setCreating(true)}><Plus size={18} />Add citizen</Button></div>} />{error && <Alert onClose={() => setError('')}>{error}</Alert>}
    <section className="panel"><div className="panel-heading panel-heading--search"><div><h2>Citizen directory</h2><p>{result.totalElements || 0} citizen records</p></div><label className="search-box"><Search size={18} /><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(0) }} placeholder="Search name, NIC or email" aria-label="Search citizens" /></label></div>
      {loading ? <SkeletonRows /> : !result.content?.length ? <EmptyState icon={UserRound} title="No citizens found" text="Change your search or add a citizen profile." /> : <div className="table-scroll"><table><thead><tr><th>Citizen</th><th>NIC</th><th>Contact</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{result.content.map((citizen) => <tr key={citizen.id}><td><strong>{citizen.name}</strong><small>ID #{citizen.id}</small></td><td>{citizen.nic}</td><td>{citizen.email}<small>{citizen.mobile}</small></td><td><StatusBadge value={citizen.status} /></td><td className="table-actions"><Button variant="ghost" onClick={() => setEditing(citizen)}>Edit</Button>{citizen.status !== 'INACTIVE' && <button className="icon-button icon-button--danger" onClick={() => deactivate(citizen)} title="Deactivate"><Trash2 size={17} /></button>}</td></tr>)}</tbody></table></div>}<Pagination page={result.number || 0} totalPages={result.totalPages || 0} onChange={setPage} />
    </section>
    {creating && <Modal title="Create citizen profile" description="Add a citizen and their verified contact details." onClose={() => setCreating(false)}><CitizenForm onClose={() => setCreating(false)} onSave={async (body) => { await citizenApi.create(body); load() }} /></Modal>}
    {editing && <Modal title="Update citizen" description={`Editing citizen #${editing.id}`} onClose={() => setEditing(null)}><CitizenForm initial={editing} onClose={() => setEditing(null)} onSave={async (body) => { await citizenApi.update(editing.id, body); load() }} /></Modal>}
    {tools && <Modal title="Administrator tools" description="Privileged account and document operations." onClose={() => setTools(false)}><AdminTools onClose={() => setTools(false)} /></Modal>}
  </>
}
